spring.application.name=polyhub
spring.datasource.url=jdbc:mysql://localhost:3306/polyhub?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.mongodb.uri=mongodb://localhost:27017/polyhub_nosql

server.port=8080

# Cấu hình giới hạn kích thước file tải lên (Fix lỗi MaxUploadSizeExceededException)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Cloudinary Configuration
cloudinary.cloud_name=dueb9a4d9
cloudinary.api_key=355974684552594
cloudinary.api_secret=RMcyJX2hM5TH7YFCUgL2-WR6I40

# Gemini AI Configuration
gemini.api.key=AIzaSyDQ8VF_dVp8dJ_SanHrr9PJ6CfWk_W_x5U
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=

# Email Sender Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nmn00525@gmail.com
spring.mail.password=xksl cywc bxha kvcn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true